import NavigationMenu from '../components/NavigationMenu';
import localFont from "next/font/local";
import type {Metadata} from "next";
import Sidebar from "@/app/components/Sidebar";
import Navbar from "@/app/components/Navbar";

const geistSans = localFont({
    src: ".././fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: ".././fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <Sidebar />
        <div className="ml-64 mt-16"> {/* Adjust margin to avoid overlap */}
            {children}
        </div>
        </body>
        </html>
    );
}